from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='hello_world'),
    path('veneer', views.veneer, name='veneer'),
    path('spc', views.spc, name='spc'),
    path('porcelain', views.porcelain, name='porcelain'),
    path('porcelain-indoor', views.porcelain_indoor, name='porcelain-indoor'),
    path('quartz', views.quartz, name='quartz'),


    path('Ammonite-Bianco', views.Ammonite_Bianco, name='Ammonite-Bianco'),
    path('Antique-Botticino-And-Black-Gold-Travertine', views.Antique_Botticino_And_Black_Gold_Travertine,
         name='Antique-Botticino-And-Black-Gold-Travertine'),
    path('Ardesia-Grigio', views.Ardesia_Grigio, name='Ardesia-Grigio'),
    path('Armani-Beige-And-Armani-Gold', views.Armani_Beige_And_Armani_Gold,
         name='Armani-Beige-And-Armani-Gold'),
    path('Armani-Gold-And-Armani-Grey', views.Armani_Gold_And_Armani_Grey,
         name='Armani-Gold-And-Armani-Grey'),
    path('Astonia-Grey', views.Astonia_Grey,
         name='Astonia-Grey'),

    path('Aldo-Beige-And-Noce-Marrone', views.Aldo_Beige_And_Noce_Marrone,
         name='Aldo-Beige-And-Noce-Marrone'),
    path('Autumn-Rustic', views.Autumn_Rustic,
         name='Autumn-Rustic'),
    path('California-Gold', views.California_Gold,
         name='California-Gold'),
    path('Copper', views.Copper,
         name='Copper'),
    path('D-Red', views.D_Red,
         name='D-Red'),
    path('Deoli-Green', views.Deoli_Green,
         name='Deoli-Green'),
    path('Himalayan-Flakes', views.Himalayan_Flakes,
         name='Himalayan-Flakes'),
    path('Galaxy', views.Galaxy,
         name='Galaxy'),
    path('ALAMO-K1082L-4', views.ALAMO_K1082L_4,
         name='ALAMO-K1082L-4'),
    path('VERONA-K1271L-2', views.VERONA_K1271L_2,
         name='VERONA-K1271L-2'),
    path('ZION-K1223-12', views.ZION_K1223_12,
         name='ZION-K1223-12'),
    path('TWILIGHT-BD82178-1', views.TWILIGHT_BD82178_1,
         name='TWILIGHT-BD82178-1'),
    path('TRENZ-88024L-7', views.TRENZ_88024L_7,
         name='TRENZ-88024L-7'),
    path('SOFIA-BD82151-10', views.SOFIA_BD82151_10,
         name='SOFIA-BD82151-10'),
    path('SEDONA-K1273-3', views.SEDONA_K1273_3,
         name='SEDONA-K1273-3'),
]
